### ISSUE TITLE
Supply power option no longer working

### ISSUE THREAD

**Issue by spezi77** [DespairFactor/marlin#2]
Some guy on sailfish has reported in my thread that with your kernel it dont work. See: https://forum.xda-developers.com/pixel/development/rom-pixel-dust-sailfish-t3585007/page14

Any idea?

**Comment by DespairFactor** [comment]
What is this feature that he is talking about?

**Comment by spezi77** [comment]
He says that it is included in stock pixel rom. It allows to supply an external device connected via USB with power.

**Comment by DespairFactor** [comment]
Nothing changed kernel side for this.
